package sckj.soams.entity;

public class HostDiskInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_disk_info.devid
     *
     * @mbggenerated
     */
    private Integer devid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_disk_info.hostid
     *
     * @mbggenerated
     */
    private String hostid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_disk_info.devname
     *
     * @mbggenerated
     */
    private String devname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_disk_info.dirname
     *
     * @mbggenerated
     */
    private String dirname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_disk_info.systype
     *
     * @mbggenerated
     */
    private String systype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_disk_info.typename
     *
     * @mbggenerated
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_disk_info.total
     *
     * @mbggenerated
     */
    private String total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_disk_info.free
     *
     * @mbggenerated
     */
    private String free;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_disk_info.used
     *
     * @mbggenerated
     */
    private String used;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_disk_info.usaged
     *
     * @mbggenerated
     */
    private String usaged;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_disk_info.devid
     *
     * @return the value of host_disk_info.devid
     *
     * @mbggenerated
     */
    public Integer getDevid() {
        return devid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_disk_info.devid
     *
     * @param devid the value for host_disk_info.devid
     *
     * @mbggenerated
     */
    public void setDevid(Integer devid) {
        this.devid = devid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_disk_info.hostid
     *
     * @return the value of host_disk_info.hostid
     *
     * @mbggenerated
     */
    public String getHostid() {
        return hostid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_disk_info.hostid
     *
     * @param hostid the value for host_disk_info.hostid
     *
     * @mbggenerated
     */
    public void setHostid(String hostid) {
        this.hostid = hostid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_disk_info.devname
     *
     * @return the value of host_disk_info.devname
     *
     * @mbggenerated
     */
    public String getDevname() {
        return devname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_disk_info.devname
     *
     * @param devname the value for host_disk_info.devname
     *
     * @mbggenerated
     */
    public void setDevname(String devname) {
        this.devname = devname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_disk_info.dirname
     *
     * @return the value of host_disk_info.dirname
     *
     * @mbggenerated
     */
    public String getDirname() {
        return dirname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_disk_info.dirname
     *
     * @param dirname the value for host_disk_info.dirname
     *
     * @mbggenerated
     */
    public void setDirname(String dirname) {
        this.dirname = dirname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_disk_info.systype
     *
     * @return the value of host_disk_info.systype
     *
     * @mbggenerated
     */
    public String getSystype() {
        return systype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_disk_info.systype
     *
     * @param systype the value for host_disk_info.systype
     *
     * @mbggenerated
     */
    public void setSystype(String systype) {
        this.systype = systype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_disk_info.typename
     *
     * @return the value of host_disk_info.typename
     *
     * @mbggenerated
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_disk_info.typename
     *
     * @param typename the value for host_disk_info.typename
     *
     * @mbggenerated
     */
    public void setTypename(String typename) {
        this.typename = typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_disk_info.total
     *
     * @return the value of host_disk_info.total
     *
     * @mbggenerated
     */
    public String getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_disk_info.total
     *
     * @param total the value for host_disk_info.total
     *
     * @mbggenerated
     */
    public void setTotal(String total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_disk_info.free
     *
     * @return the value of host_disk_info.free
     *
     * @mbggenerated
     */
    public String getFree() {
        return free;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_disk_info.free
     *
     * @param free the value for host_disk_info.free
     *
     * @mbggenerated
     */
    public void setFree(String free) {
        this.free = free;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_disk_info.used
     *
     * @return the value of host_disk_info.used
     *
     * @mbggenerated
     */
    public String getUsed() {
        return used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_disk_info.used
     *
     * @param used the value for host_disk_info.used
     *
     * @mbggenerated
     */
    public void setUsed(String used) {
        this.used = used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_disk_info.usaged
     *
     * @return the value of host_disk_info.usaged
     *
     * @mbggenerated
     */
    public String getUsaged() {
        return usaged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_disk_info.usaged
     *
     * @param usaged the value for host_disk_info.usaged
     *
     * @mbggenerated
     */
    public void setUsaged(String usaged) {
        this.usaged = usaged;
    }
}