package sckj.soams.entity;

public class HostCpuInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_cpu_info.hostid
     *
     * @mbggenerated
     */
    private String hostid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_cpu_info.cache_size
     *
     * @mbggenerated
     */
    private String cache_size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_cpu_info.cpu_cores
     *
     * @mbggenerated
     */
    private Integer cpu_cores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_cpu_info.vendor
     *
     * @mbggenerated
     */
    private String vendor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_cpu_info.mhz
     *
     * @mbggenerated
     */
    private String mhz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_cpu_info.model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_cpu_info.hostid
     *
     * @return the value of host_cpu_info.hostid
     *
     * @mbggenerated
     */
    public String getHostid() {
        return hostid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_cpu_info.hostid
     *
     * @param hostid the value for host_cpu_info.hostid
     *
     * @mbggenerated
     */
    public void setHostid(String hostid) {
        this.hostid = hostid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_cpu_info.cache_size
     *
     * @return the value of host_cpu_info.cache_size
     *
     * @mbggenerated
     */
    public String getCache_size() {
        return cache_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_cpu_info.cache_size
     *
     * @param cache_size the value for host_cpu_info.cache_size
     *
     * @mbggenerated
     */
    public void setCache_size(String cache_size) {
        this.cache_size = cache_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_cpu_info.cpu_cores
     *
     * @return the value of host_cpu_info.cpu_cores
     *
     * @mbggenerated
     */
    public Integer getCpu_cores() {
        return cpu_cores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_cpu_info.cpu_cores
     *
     * @param cpu_cores the value for host_cpu_info.cpu_cores
     *
     * @mbggenerated
     */
    public void setCpu_cores(Integer cpu_cores) {
        this.cpu_cores = cpu_cores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_cpu_info.vendor
     *
     * @return the value of host_cpu_info.vendor
     *
     * @mbggenerated
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_cpu_info.vendor
     *
     * @param vendor the value for host_cpu_info.vendor
     *
     * @mbggenerated
     */
    public void setVendor(String vendor) {
        this.vendor = vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_cpu_info.mhz
     *
     * @return the value of host_cpu_info.mhz
     *
     * @mbggenerated
     */
    public String getMhz() {
        return mhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_cpu_info.mhz
     *
     * @param mhz the value for host_cpu_info.mhz
     *
     * @mbggenerated
     */
    public void setMhz(String mhz) {
        this.mhz = mhz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_cpu_info.model
     *
     * @return the value of host_cpu_info.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_cpu_info.model
     *
     * @param model the value for host_cpu_info.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model;
    }
}