package sckj.soams.entity;

import java.util.Date;

public class HostNetLogs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_net_logs.seq
     *
     * @mbggenerated
     */
    private Long seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_net_logs.recdt
     *
     * @mbggenerated
     */
    private Date recdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_net_logs.hostid
     *
     * @mbggenerated
     */
    private String hostid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_net_logs.netname
     *
     * @mbggenerated
     */
    private String netname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_net_logs.rxbps
     *
     * @mbggenerated
     */
    private String rxbps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_net_logs.txbps
     *
     * @mbggenerated
     */
    private String txbps;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_net_logs.seq
     *
     * @return the value of host_net_logs.seq
     *
     * @mbggenerated
     */
    public Long getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_net_logs.seq
     *
     * @param seq the value for host_net_logs.seq
     *
     * @mbggenerated
     */
    public void setSeq(Long seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_net_logs.recdt
     *
     * @return the value of host_net_logs.recdt
     *
     * @mbggenerated
     */
    public Date getRecdt() {
        return recdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_net_logs.recdt
     *
     * @param recdt the value for host_net_logs.recdt
     *
     * @mbggenerated
     */
    public void setRecdt(Date recdt) {
        this.recdt = recdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_net_logs.hostid
     *
     * @return the value of host_net_logs.hostid
     *
     * @mbggenerated
     */
    public String getHostid() {
        return hostid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_net_logs.hostid
     *
     * @param hostid the value for host_net_logs.hostid
     *
     * @mbggenerated
     */
    public void setHostid(String hostid) {
        this.hostid = hostid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_net_logs.netname
     *
     * @return the value of host_net_logs.netname
     *
     * @mbggenerated
     */
    public String getNetname() {
        return netname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_net_logs.netname
     *
     * @param netname the value for host_net_logs.netname
     *
     * @mbggenerated
     */
    public void setNetname(String netname) {
        this.netname = netname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_net_logs.rxbps
     *
     * @return the value of host_net_logs.rxbps
     *
     * @mbggenerated
     */
    public String getRxbps() {
        return rxbps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_net_logs.rxbps
     *
     * @param rxbps the value for host_net_logs.rxbps
     *
     * @mbggenerated
     */
    public void setRxbps(String rxbps) {
        this.rxbps = rxbps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_net_logs.txbps
     *
     * @return the value of host_net_logs.txbps
     *
     * @mbggenerated
     */
    public String getTxbps() {
        return txbps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_net_logs.txbps
     *
     * @param txbps the value for host_net_logs.txbps
     *
     * @mbggenerated
     */
    public void setTxbps(String txbps) {
        this.txbps = txbps;
    }
}