package sckj.soams.entity;

public class HostNetInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_net_info.hostid
     *
     * @mbggenerated
     */
    private String hostid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_net_info.netname
     *
     * @mbggenerated
     */
    private String netname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_net_info.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_net_info.netmask
     *
     * @mbggenerated
     */
    private String netmask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_net_info.macaddr
     *
     * @mbggenerated
     */
    private String macaddr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_net_info.hostid
     *
     * @return the value of host_net_info.hostid
     *
     * @mbggenerated
     */
    public String getHostid() {
        return hostid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_net_info.hostid
     *
     * @param hostid the value for host_net_info.hostid
     *
     * @mbggenerated
     */
    public void setHostid(String hostid) {
        this.hostid = hostid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_net_info.netname
     *
     * @return the value of host_net_info.netname
     *
     * @mbggenerated
     */
    public String getNetname() {
        return netname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_net_info.netname
     *
     * @param netname the value for host_net_info.netname
     *
     * @mbggenerated
     */
    public void setNetname(String netname) {
        this.netname = netname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_net_info.ip
     *
     * @return the value of host_net_info.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_net_info.ip
     *
     * @param ip the value for host_net_info.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_net_info.netmask
     *
     * @return the value of host_net_info.netmask
     *
     * @mbggenerated
     */
    public String getNetmask() {
        return netmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_net_info.netmask
     *
     * @param netmask the value for host_net_info.netmask
     *
     * @mbggenerated
     */
    public void setNetmask(String netmask) {
        this.netmask = netmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_net_info.macaddr
     *
     * @return the value of host_net_info.macaddr
     *
     * @mbggenerated
     */
    public String getMacaddr() {
        return macaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_net_info.macaddr
     *
     * @param macaddr the value for host_net_info.macaddr
     *
     * @mbggenerated
     */
    public void setMacaddr(String macaddr) {
        this.macaddr = macaddr;
    }
}