package sckj.soams.entity;

import java.util.Date;

public class HostCpuLogs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_cpu_logs.recdt
     *
     * @mbggenerated
     */
    private Date recdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_cpu_logs.hostid
     *
     * @mbggenerated
     */
    private String hostid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_cpu_logs.user
     *
     * @mbggenerated
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_cpu_logs.sys
     *
     * @mbggenerated
     */
    private String sys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_cpu_logs.idle
     *
     * @mbggenerated
     */
    private String idle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_cpu_logs.wait
     *
     * @mbggenerated
     */
    private String wait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_cpu_logs.nice
     *
     * @mbggenerated
     */
    private String nice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column host_cpu_logs.combined
     *
     * @mbggenerated
     */
    private String combined;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_cpu_logs.recdt
     *
     * @return the value of host_cpu_logs.recdt
     *
     * @mbggenerated
     */
    public Date getRecdt() {
        return recdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_cpu_logs.recdt
     *
     * @param recdt the value for host_cpu_logs.recdt
     *
     * @mbggenerated
     */
    public void setRecdt(Date recdt) {
        this.recdt = recdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_cpu_logs.hostid
     *
     * @return the value of host_cpu_logs.hostid
     *
     * @mbggenerated
     */
    public String getHostid() {
        return hostid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_cpu_logs.hostid
     *
     * @param hostid the value for host_cpu_logs.hostid
     *
     * @mbggenerated
     */
    public void setHostid(String hostid) {
        this.hostid = hostid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_cpu_logs.user
     *
     * @return the value of host_cpu_logs.user
     *
     * @mbggenerated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_cpu_logs.user
     *
     * @param user the value for host_cpu_logs.user
     *
     * @mbggenerated
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_cpu_logs.sys
     *
     * @return the value of host_cpu_logs.sys
     *
     * @mbggenerated
     */
    public String getSys() {
        return sys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_cpu_logs.sys
     *
     * @param sys the value for host_cpu_logs.sys
     *
     * @mbggenerated
     */
    public void setSys(String sys) {
        this.sys = sys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_cpu_logs.idle
     *
     * @return the value of host_cpu_logs.idle
     *
     * @mbggenerated
     */
    public String getIdle() {
        return idle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_cpu_logs.idle
     *
     * @param idle the value for host_cpu_logs.idle
     *
     * @mbggenerated
     */
    public void setIdle(String idle) {
        this.idle = idle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_cpu_logs.wait
     *
     * @return the value of host_cpu_logs.wait
     *
     * @mbggenerated
     */
    public String getWait() {
        return wait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_cpu_logs.wait
     *
     * @param wait the value for host_cpu_logs.wait
     *
     * @mbggenerated
     */
    public void setWait(String wait) {
        this.wait = wait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_cpu_logs.nice
     *
     * @return the value of host_cpu_logs.nice
     *
     * @mbggenerated
     */
    public String getNice() {
        return nice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_cpu_logs.nice
     *
     * @param nice the value for host_cpu_logs.nice
     *
     * @mbggenerated
     */
    public void setNice(String nice) {
        this.nice = nice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column host_cpu_logs.combined
     *
     * @return the value of host_cpu_logs.combined
     *
     * @mbggenerated
     */
    public String getCombined() {
        return combined;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column host_cpu_logs.combined
     *
     * @param combined the value for host_cpu_logs.combined
     *
     * @mbggenerated
     */
    public void setCombined(String combined) {
        this.combined = combined;
    }
}