package sckj.soams.entity;

import java.util.Date;

public class Hosts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosts.hostid
     *
     * @mbggenerated
     */
    private String hostid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosts.hostname
     *
     * @mbggenerated
     */
    private String hostname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosts.othername
     *
     * @mbggenerated
     */
    private String othername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosts.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosts.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosts.heartbeat
     *
     * @mbggenerated
     */
    private Date heartbeat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosts.memtotal
     *
     * @mbggenerated
     */
    private String memtotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosts.labels
     *
     * @mbggenerated
     */
    private String labels;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosts.hostid
     *
     * @return the value of hosts.hostid
     *
     * @mbggenerated
     */
    public String getHostid() {
        return hostid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosts.hostid
     *
     * @param hostid the value for hosts.hostid
     *
     * @mbggenerated
     */
    public void setHostid(String hostid) {
        this.hostid = hostid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosts.hostname
     *
     * @return the value of hosts.hostname
     *
     * @mbggenerated
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosts.hostname
     *
     * @param hostname the value for hosts.hostname
     *
     * @mbggenerated
     */
    public void setHostname(String hostname) {
        this.hostname = hostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosts.othername
     *
     * @return the value of hosts.othername
     *
     * @mbggenerated
     */
    public String getOthername() {
        return othername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosts.othername
     *
     * @param othername the value for hosts.othername
     *
     * @mbggenerated
     */
    public void setOthername(String othername) {
        this.othername = othername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosts.ip
     *
     * @return the value of hosts.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosts.ip
     *
     * @param ip the value for hosts.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosts.status
     *
     * @return the value of hosts.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosts.status
     *
     * @param status the value for hosts.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosts.heartbeat
     *
     * @return the value of hosts.heartbeat
     *
     * @mbggenerated
     */
    public Date getHeartbeat() {
        return heartbeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosts.heartbeat
     *
     * @param heartbeat the value for hosts.heartbeat
     *
     * @mbggenerated
     */
    public void setHeartbeat(Date heartbeat) {
        this.heartbeat = heartbeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosts.memtotal
     *
     * @return the value of hosts.memtotal
     *
     * @mbggenerated
     */
    public String getMemtotal() {
        return memtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosts.memtotal
     *
     * @param memtotal the value for hosts.memtotal
     *
     * @mbggenerated
     */
    public void setMemtotal(String memtotal) {
        this.memtotal = memtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosts.labels
     *
     * @return the value of hosts.labels
     *
     * @mbggenerated
     */
    public String getLabels() {
        return labels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosts.labels
     *
     * @param labels the value for hosts.labels
     *
     * @mbggenerated
     */
    public void setLabels(String labels) {
        this.labels = labels;
    }
    
    private String osname;
    
    public String getOsname() {
        return osname;
    }
    
    public void setOsname(String osname) {
        this.osname = osname;
    }
    
    private String osversion;
    
    public String getOsversion() {
        return osversion;
    }
    
    public void setOsversion(String osversion) {
        this.osversion = osversion;
    }
    
    private String osarch;
    
    public String getOsarch() {
        return osarch;
    }
    
    public void setOsarch(String osarch) {
        this.osarch = osarch;
    }
}