package sckj.soams.entity;

import java.util.Date;

public class InvokeChain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invokechain.invoke_seq
     *
     * @mbggenerated
     */
    private Long invoke_seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invokechain.invoke_dt
     *
     * @mbggenerated
     */
    private String invoke_dt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invokechain.application
     *
     * @mbggenerated
     */
    private String application;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invokechain.fromip
     *
     * @mbggenerated
     */
    private String fromip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invokechain.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invokechain.traceid
     *
     * @mbggenerated
     */
    private String traceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invokechain.fromrpcid
     *
     * @mbggenerated
     */
    private String fromrpcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invokechain.rpcid
     *
     * @mbggenerated
     */
    private String rpcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invokechain.method
     *
     * @mbggenerated
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invokechain.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invokechain.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invokechain.requesturl
     *
     * @mbggenerated
     */
    private String requesturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invokechain.timeelapsed
     *
     * @mbggenerated
     */
    private String timeelapsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column invokechain.createdt
     *
     * @mbggenerated
     */
    private Date createdt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invokechain.invoke_seq
     *
     * @return the value of invokechain.invoke_seq
     *
     * @mbggenerated
     */
    public Long getInvoke_seq() {
        return invoke_seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invokechain.invoke_seq
     *
     * @param invoke_seq the value for invokechain.invoke_seq
     *
     * @mbggenerated
     */
    public void setInvoke_seq(Long invoke_seq) {
        this.invoke_seq = invoke_seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invokechain.invoke_dt
     *
     * @return the value of invokechain.invoke_dt
     *
     * @mbggenerated
     */
    public String getInvoke_dt() {
        return invoke_dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invokechain.invoke_dt
     *
     * @param invoke_dt the value for invokechain.invoke_dt
     *
     * @mbggenerated
     */
    public void setInvoke_dt(String invoke_dt) {
        this.invoke_dt = invoke_dt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invokechain.application
     *
     * @return the value of invokechain.application
     *
     * @mbggenerated
     */
    public String getApplication() {
        return application;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invokechain.application
     *
     * @param application the value for invokechain.application
     *
     * @mbggenerated
     */
    public void setApplication(String application) {
        this.application = application;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invokechain.fromip
     *
     * @return the value of invokechain.fromip
     *
     * @mbggenerated
     */
    public String getFromip() {
        return fromip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invokechain.fromip
     *
     * @param fromip the value for invokechain.fromip
     *
     * @mbggenerated
     */
    public void setFromip(String fromip) {
        this.fromip = fromip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invokechain.ip
     *
     * @return the value of invokechain.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invokechain.ip
     *
     * @param ip the value for invokechain.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invokechain.traceid
     *
     * @return the value of invokechain.traceid
     *
     * @mbggenerated
     */
    public String getTraceid() {
        return traceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invokechain.traceid
     *
     * @param traceid the value for invokechain.traceid
     *
     * @mbggenerated
     */
    public void setTraceid(String traceid) {
        this.traceid = traceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invokechain.fromrpcid
     *
     * @return the value of invokechain.fromrpcid
     *
     * @mbggenerated
     */
    public String getFromrpcid() {
        return fromrpcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invokechain.fromrpcid
     *
     * @param fromrpcid the value for invokechain.fromrpcid
     *
     * @mbggenerated
     */
    public void setFromrpcid(String fromrpcid) {
        this.fromrpcid = fromrpcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invokechain.rpcid
     *
     * @return the value of invokechain.rpcid
     *
     * @mbggenerated
     */
    public String getRpcid() {
        return rpcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invokechain.rpcid
     *
     * @param rpcid the value for invokechain.rpcid
     *
     * @mbggenerated
     */
    public void setRpcid(String rpcid) {
        this.rpcid = rpcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invokechain.method
     *
     * @return the value of invokechain.method
     *
     * @mbggenerated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invokechain.method
     *
     * @param method the value for invokechain.method
     *
     * @mbggenerated
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invokechain.status
     *
     * @return the value of invokechain.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invokechain.status
     *
     * @param status the value for invokechain.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invokechain.type
     *
     * @return the value of invokechain.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invokechain.type
     *
     * @param type the value for invokechain.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invokechain.requesturl
     *
     * @return the value of invokechain.requesturl
     *
     * @mbggenerated
     */
    public String getRequesturl() {
        return requesturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invokechain.requesturl
     *
     * @param requesturl the value for invokechain.requesturl
     *
     * @mbggenerated
     */
    public void setRequesturl(String requesturl) {
        this.requesturl = requesturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invokechain.timeelapsed
     *
     * @return the value of invokechain.timeelapsed
     *
     * @mbggenerated
     */
    public String getTimeelapsed() {
        return timeelapsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invokechain.timeelapsed
     *
     * @param timeelapsed the value for invokechain.timeelapsed
     *
     * @mbggenerated
     */
    public void setTimeelapsed(String timeelapsed) {
        this.timeelapsed = timeelapsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column invokechain.createdt
     *
     * @return the value of invokechain.createdt
     *
     * @mbggenerated
     */
    public Date getCreatedt() {
        return createdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column invokechain.createdt
     *
     * @param createdt the value for invokechain.createdt
     *
     * @mbggenerated
     */
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }
}