package sckj.soams.entity;

import java.util.Date;

public class LoginLogs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_logs.loginseq
     *
     * @mbggenerated
     */
    private Integer loginseq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_logs.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_logs.logindt
     *
     * @mbggenerated
     */
    private Date logindt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_logs.loginip
     *
     * @mbggenerated
     */
    private String loginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_logs.agent
     *
     * @mbggenerated
     */
    private String agent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_logs.loginseq
     *
     * @return the value of login_logs.loginseq
     *
     * @mbggenerated
     */
    public Integer getLoginseq() {
        return loginseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_logs.loginseq
     *
     * @param loginseq the value for login_logs.loginseq
     *
     * @mbggenerated
     */
    public void setLoginseq(Integer loginseq) {
        this.loginseq = loginseq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_logs.userid
     *
     * @return the value of login_logs.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_logs.userid
     *
     * @param userid the value for login_logs.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_logs.logindt
     *
     * @return the value of login_logs.logindt
     *
     * @mbggenerated
     */
    public Date getLogindt() {
        return logindt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_logs.logindt
     *
     * @param logindt the value for login_logs.logindt
     *
     * @mbggenerated
     */
    public void setLogindt(Date logindt) {
        this.logindt = logindt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_logs.loginip
     *
     * @return the value of login_logs.loginip
     *
     * @mbggenerated
     */
    public String getLoginip() {
        return loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_logs.loginip
     *
     * @param loginip the value for login_logs.loginip
     *
     * @mbggenerated
     */
    public void setLoginip(String loginip) {
        this.loginip = loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_logs.agent
     *
     * @return the value of login_logs.agent
     *
     * @mbggenerated
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_logs.agent
     *
     * @param agent the value for login_logs.agent
     *
     * @mbggenerated
     */
    public void setAgent(String agent) {
        this.agent = agent;
    }
}