package sckj.soams.entity;

import java.util.Date;

public class MemSwapLogs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_swap_logs.hostid
     *
     * @mbggenerated
     */
    private String hostid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_swap_logs.recdt
     *
     * @mbggenerated
     */
    private Date recdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_swap_logs.total
     *
     * @mbggenerated
     */
    private String total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_swap_logs.used
     *
     * @mbggenerated
     */
    private String used;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_swap_logs.free
     *
     * @mbggenerated
     */
    private String free;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_swap_logs.ram
     *
     * @mbggenerated
     */
    private String ram;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_swap_logs.hostid
     *
     * @return the value of mem_swap_logs.hostid
     *
     * @mbggenerated
     */
    public String getHostid() {
        return hostid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_swap_logs.hostid
     *
     * @param hostid the value for mem_swap_logs.hostid
     *
     * @mbggenerated
     */
    public void setHostid(String hostid) {
        this.hostid = hostid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_swap_logs.recdt
     *
     * @return the value of mem_swap_logs.recdt
     *
     * @mbggenerated
     */
    public Date getRecdt() {
        return recdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_swap_logs.recdt
     *
     * @param recdt the value for mem_swap_logs.recdt
     *
     * @mbggenerated
     */
    public void setRecdt(Date recdt) {
        this.recdt = recdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_swap_logs.total
     *
     * @return the value of mem_swap_logs.total
     *
     * @mbggenerated
     */
    public String getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_swap_logs.total
     *
     * @param total the value for mem_swap_logs.total
     *
     * @mbggenerated
     */
    public void setTotal(String total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_swap_logs.used
     *
     * @return the value of mem_swap_logs.used
     *
     * @mbggenerated
     */
    public String getUsed() {
        return used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_swap_logs.used
     *
     * @param used the value for mem_swap_logs.used
     *
     * @mbggenerated
     */
    public void setUsed(String used) {
        this.used = used;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_swap_logs.free
     *
     * @return the value of mem_swap_logs.free
     *
     * @mbggenerated
     */
    public String getFree() {
        return free;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_swap_logs.free
     *
     * @param free the value for mem_swap_logs.free
     *
     * @mbggenerated
     */
    public void setFree(String free) {
        this.free = free;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_swap_logs.ram
     *
     * @return the value of mem_swap_logs.ram
     *
     * @mbggenerated
     */
    public String getRam() {
        return ram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_swap_logs.ram
     *
     * @param ram the value for mem_swap_logs.ram
     *
     * @mbggenerated
     */
    public void setRam(String ram) {
        this.ram = ram;
    }
}