package sckj.soams.entity;

public class Menus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.menuid
     *
     * @mbggenerated
     */
    private Integer menuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.menutext
     *
     * @mbggenerated
     */
    private String menutext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.menuurl
     *
     * @mbggenerated
     */
    private String menuurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.parentid
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menus.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.menuid
     *
     * @return the value of menus.menuid
     *
     * @mbggenerated
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.menuid
     *
     * @param menuid the value for menus.menuid
     *
     * @mbggenerated
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.menutext
     *
     * @return the value of menus.menutext
     *
     * @mbggenerated
     */
    public String getMenutext() {
        return menutext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.menutext
     *
     * @param menutext the value for menus.menutext
     *
     * @mbggenerated
     */
    public void setMenutext(String menutext) {
        this.menutext = menutext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.menuurl
     *
     * @return the value of menus.menuurl
     *
     * @mbggenerated
     */
    public String getMenuurl() {
        return menuurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.menuurl
     *
     * @param menuurl the value for menus.menuurl
     *
     * @mbggenerated
     */
    public void setMenuurl(String menuurl) {
        this.menuurl = menuurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.parentid
     *
     * @return the value of menus.parentid
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.parentid
     *
     * @param parentid the value for menus.parentid
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.note
     *
     * @return the value of menus.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.note
     *
     * @param note the value for menus.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menus.icon
     *
     * @return the value of menus.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menus.icon
     *
     * @param icon the value for menus.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }
}