package sckj.soams.entity;

import java.util.Date;

public class OtherLogs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherlogs.logid
     *
     * @mbggenerated
     */
    private Long logid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherlogs.logtext
     *
     * @mbggenerated
     */
    private String logtext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column otherlogs.createdt
     *
     * @mbggenerated
     */
    private Date createdt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherlogs.logid
     *
     * @return the value of otherlogs.logid
     *
     * @mbggenerated
     */
    public Long getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherlogs.logid
     *
     * @param logid the value for otherlogs.logid
     *
     * @mbggenerated
     */
    public void setLogid(Long logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherlogs.logtext
     *
     * @return the value of otherlogs.logtext
     *
     * @mbggenerated
     */
    public String getLogtext() {
        return logtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherlogs.logtext
     *
     * @param logtext the value for otherlogs.logtext
     *
     * @mbggenerated
     */
    public void setLogtext(String logtext) {
        this.logtext = logtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column otherlogs.createdt
     *
     * @return the value of otherlogs.createdt
     *
     * @mbggenerated
     */
    public Date getCreatedt() {
        return createdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column otherlogs.createdt
     *
     * @param createdt the value for otherlogs.createdt
     *
     * @mbggenerated
     */
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }
}