package sckj.soams.mapping;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

import sckj.soams.bean.HostsBean;
import sckj.soams.entity.Hosts;

public interface HostsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosts
     *
     * @mbggenerated
     */
    @Delete({
        "delete from hosts",
        "where hostid = #{hostid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String hostid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosts
     *
     * @mbggenerated
     */
    @Insert({
        "insert into hosts (hostid, hostname, ",
        "othername, ip, status, ",
        "heartbeat, memtotal, ",
        "labels)",
        "values (#{hostid,jdbcType=VARCHAR}, #{hostname,jdbcType=VARCHAR}, ",
        "#{othername,jdbcType=VARCHAR}, #{ip,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, ",
        "#{heartbeat,jdbcType=TIMESTAMP}, #{memtotal,jdbcType=VARCHAR}, ",
        "#{labels,jdbcType=VARCHAR})"
    })
    int insert(Hosts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosts
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "hostid, hostname, othername, ip, status, heartbeat, memtotal, labels, osname, osversion, osarch ",
        "from hosts",
        "where hostid = #{hostid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="hostid", property="hostid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="hostname", property="hostname", jdbcType=JdbcType.VARCHAR),
        @Result(column="othername", property="othername", jdbcType=JdbcType.VARCHAR),
        @Result(column="ip", property="ip", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="heartbeat", property="heartbeat", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="memtotal", property="memtotal", jdbcType=JdbcType.VARCHAR),
        @Result(column="labels", property="labels", jdbcType=JdbcType.VARCHAR),
        @Result(column="osname", property="osname", jdbcType=JdbcType.VARCHAR),
        @Result(column="osversion", property="osversion", jdbcType=JdbcType.VARCHAR),
        @Result(column="osarch", property="osarch", jdbcType=JdbcType.VARCHAR)
    })
    Hosts selectByPrimaryKey(String hostid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosts
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "hostid, hostname, othername, ip, status, heartbeat, memtotal, labels, osname, osversion, osarch",
        "from hosts"
    })
    @Results({
        @Result(column="hostid", property="hostid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="hostname", property="hostname", jdbcType=JdbcType.VARCHAR),
        @Result(column="othername", property="othername", jdbcType=JdbcType.VARCHAR),
        @Result(column="ip", property="ip", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="heartbeat", property="heartbeat", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="memtotal", property="memtotal", jdbcType=JdbcType.VARCHAR),
        @Result(column="labels", property="labels", jdbcType=JdbcType.VARCHAR),
        @Result(column="osname", property="osname", jdbcType=JdbcType.VARCHAR),
        @Result(column="osversion", property="osversion", jdbcType=JdbcType.VARCHAR),
        @Result(column="osarch", property="osarch", jdbcType=JdbcType.VARCHAR)
    })
    List<HostsBean> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosts
     *
     * @mbggenerated
     */
    @Update({
        "update hosts",
        "set hostname = #{hostname,jdbcType=VARCHAR},",
          "othername = #{othername,jdbcType=VARCHAR},",
          "ip = #{ip,jdbcType=VARCHAR},",
          "status = #{status,jdbcType=VARCHAR},",
          "heartbeat = #{heartbeat,jdbcType=TIMESTAMP},",
          "memtotal = #{memtotal,jdbcType=VARCHAR},",
          "labels = #{labels,jdbcType=VARCHAR}",
        "where hostid = #{hostid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Hosts record);
    
    @Select({
        "select",
        "hostid, hostname, othername, ip, status, heartbeat, memtotal, labels, osname, osversion, osarch",
        "from hosts",
        " where 1=1 and IF(#{ip,jdbcType=VARCHAR}, ip like CONCAT('%',#{ip,jdbcType=VARCHAR},'%'), 1=1)"
    })
    @Results({
        @Result(column="hostid", property="hostid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="hostname", property="hostname", jdbcType=JdbcType.VARCHAR),
        @Result(column="othername", property="othername", jdbcType=JdbcType.VARCHAR),
        @Result(column="ip", property="ip", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="heartbeat", property="heartbeat", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="memtotal", property="memtotal", jdbcType=JdbcType.VARCHAR),
        @Result(column="labels", property="labels", jdbcType=JdbcType.VARCHAR),
        @Result(column="osname", property="osname", jdbcType=JdbcType.VARCHAR),
        @Result(column="osversion", property="osversion", jdbcType=JdbcType.VARCHAR),
        @Result(column="osarch", property="osarch", jdbcType=JdbcType.VARCHAR)
    })
    List<HostsBean> getAll(HostsBean bean);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosts
     *
     * @mbggenerated
     */
    @Update({
        "update hosts",
        "set othername = #{othername,jdbcType=VARCHAR},",
          "labels = #{labels,jdbcType=VARCHAR}",
        "where hostid = #{hostid,jdbcType=VARCHAR}"
    })
    int updatebyhostid(HostsBean bean);
}