package sckj.soams.mapping;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import sckj.soams.entity.HostNetInfo;

public interface HostNetInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_net_info
     *
     * @mbggenerated
     */
    @Delete({
        "delete from host_net_info",
        "where hostid = #{hostid,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String hostid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_net_info
     *
     * @mbggenerated
     */
    @Insert({
        "insert into host_net_info (hostid, netname, ",
        "ip, netmask, macaddr)",
        "values (#{hostid,jdbcType=VARCHAR}, #{netname,jdbcType=VARCHAR}, ",
        "#{ip,jdbcType=VARCHAR}, #{netmask,jdbcType=VARCHAR}, #{macaddr,jdbcType=VARCHAR})"
    })
    int insert(HostNetInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_net_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "hostid, netname, ip, netmask, macaddr",
        "from host_net_info",
        "where hostid = #{hostid,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="hostid", property="hostid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="netname", property="netname", jdbcType=JdbcType.VARCHAR),
        @Result(column="ip", property="ip", jdbcType=JdbcType.VARCHAR),
        @Result(column="netmask", property="netmask", jdbcType=JdbcType.VARCHAR),
        @Result(column="macaddr", property="macaddr", jdbcType=JdbcType.VARCHAR)
    })
    HostNetInfo selectByPrimaryKey(String hostid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_net_info
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "hostid, netname, ip, netmask, macaddr",
        "from host_net_info"
    })
    @Results({
        @Result(column="hostid", property="hostid", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="netname", property="netname", jdbcType=JdbcType.VARCHAR),
        @Result(column="ip", property="ip", jdbcType=JdbcType.VARCHAR),
        @Result(column="netmask", property="netmask", jdbcType=JdbcType.VARCHAR),
        @Result(column="macaddr", property="macaddr", jdbcType=JdbcType.VARCHAR)
    })
    List<HostNetInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table host_net_info
     *
     * @mbggenerated
     */
    @Update({
        "update host_net_info",
        "set netname = #{netname,jdbcType=VARCHAR},",
          "ip = #{ip,jdbcType=VARCHAR},",
          "netmask = #{netmask,jdbcType=VARCHAR},",
          "macaddr = #{macaddr,jdbcType=VARCHAR}",
        "where hostid = #{hostid,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(HostNetInfo record);
}