package sckj.soams.mapping;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import sckj.soams.entity.Menus;

public interface MenusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbggenerated
     */
    @Delete({
        "delete from menus",
        "where menuid = #{menuid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbggenerated
     */
    @Insert({
        "insert into menus (menuid, menutext, ",
        "menuurl, parentid, ",
        "note, icon)",
        "values (#{menuid,jdbcType=INTEGER}, #{menutext,jdbcType=VARCHAR}, ",
        "#{menuurl,jdbcType=VARCHAR}, #{parentid,jdbcType=INTEGER}, ",
        "#{note,jdbcType=VARCHAR}, #{icon,jdbcType=VARCHAR})"
    })
    int insert(Menus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "menuid, menutext, menuurl, parentid, note, icon",
        "from menus",
        "where menuid = #{menuid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="menuid", property="menuid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="menutext", property="menutext", jdbcType=JdbcType.VARCHAR),
        @Result(column="menuurl", property="menuurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="parentid", property="parentid", jdbcType=JdbcType.INTEGER),
        @Result(column="note", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="icon", property="icon", jdbcType=JdbcType.VARCHAR)
    })
    Menus selectByPrimaryKey(Integer menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "menuid, menutext, menuurl, parentid, note, icon",
        "from menus"
    })
    @Results({
        @Result(column="menuid", property="menuid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="menutext", property="menutext", jdbcType=JdbcType.VARCHAR),
        @Result(column="menuurl", property="menuurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="parentid", property="parentid", jdbcType=JdbcType.INTEGER),
        @Result(column="note", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="icon", property="icon", jdbcType=JdbcType.VARCHAR)
    })
    List<Menus> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menus
     *
     * @mbggenerated
     */
    @Update({
        "update menus",
        "set menutext = #{menutext,jdbcType=VARCHAR},",
          "menuurl = #{menuurl,jdbcType=VARCHAR},",
          "parentid = #{parentid,jdbcType=INTEGER},",
          "note = #{note,jdbcType=VARCHAR},",
          "icon = #{icon,jdbcType=VARCHAR}",
        "where menuid = #{menuid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Menus record);
}