package sckj.soams.mapping;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import sckj.soams.entity.OtherLogs;

public interface OtherLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otherlogs
     *
     * @mbggenerated
     */
    @Delete({
        "delete from otherlogs",
        "where logid = #{logid,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otherlogs
     *
     * @mbggenerated
     */
    @Insert({
        "insert into otherlogs (logid, logtext, ",
        "createdt)",
        "values (#{logid,jdbcType=BIGINT}, #{logtext,jdbcType=VARCHAR}, ",
        "#{createdt,jdbcType=TIMESTAMP})"
    })
    int insert(OtherLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otherlogs
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "logid, logtext, createdt",
        "from otherlogs",
        "where logid = #{logid,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="logid", property="logid", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="logtext", property="logtext", jdbcType=JdbcType.VARCHAR),
        @Result(column="createdt", property="createdt", jdbcType=JdbcType.TIMESTAMP)
    })
    OtherLogs selectByPrimaryKey(Long logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otherlogs
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "logid, logtext, createdt",
        "from otherlogs"
    })
    @Results({
        @Result(column="logid", property="logid", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="logtext", property="logtext", jdbcType=JdbcType.VARCHAR),
        @Result(column="createdt", property="createdt", jdbcType=JdbcType.TIMESTAMP)
    })
    List<OtherLogs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otherlogs
     *
     * @mbggenerated
     */
    @Update({
        "update otherlogs",
        "set logtext = #{logtext,jdbcType=VARCHAR},",
          "createdt = #{createdt,jdbcType=TIMESTAMP}",
        "where logid = #{logid,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OtherLogs record);
}