package sckj.soams.mapping;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

import sckj.soams.entity.SysUser;

public interface SysUserMapper {
	
    @Delete({
        "delete from sysuser",
        "where logid = #{userid,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otherlogs
     *
     * @mbggenerated
     */
    @Insert({
        "insert into sysuser (userid, loginname, username, password, flag, telphone, qq, email, weixin, department, note)",
        "values (#{userid,jdbcType=BIGINT}, #{loginname,jdbcType=VARCHAR}, #{username,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, #{flag,jdbcType=BIGINT} ",
        ",#{telphone,jdbcType=VARCHAR}, #{qq,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, #{weixin,jdbcType=VARCHAR} ",
        ", #{department,jdbcType=VARCHAR}, #{note,jdbcType=VARCHAR})"
    })
    int insert(SysUser user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otherlogs
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "userid, loginname, username, password, flag, telphone, qq, email, weixin, department, note ",
        "from sysuser",
        "where userid = #{userid,jdbcType=BIGINT}"
    })
    @Results({
        @Result(column="userid", property="userid", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="loginname", property="loginname", jdbcType=JdbcType.VARCHAR),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="flag", property="flag", jdbcType=JdbcType.BIGINT),
        @Result(column="telphone", property="telphone", jdbcType=JdbcType.VARCHAR),
        @Result(column="qq", property="qq", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="weixin", property="weixin", jdbcType=JdbcType.VARCHAR),
        @Result(column="department", property="department", jdbcType=JdbcType.VARCHAR),
        @Result(column="note", property="note", jdbcType=JdbcType.VARCHAR)
    })
    SysUser selectByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otherlogs
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "userid, loginname, username, password, flag, telphone, qq, email, weixin, department, note ",
        "from sysuser"
    })
    @Results({
    	@Result(column="userid", property="userid", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="loginname", property="loginname", jdbcType=JdbcType.VARCHAR),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="flag", property="flag", jdbcType=JdbcType.BIGINT),
        @Result(column="telphone", property="telphone", jdbcType=JdbcType.VARCHAR),
        @Result(column="qq", property="qq", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="weixin", property="weixin", jdbcType=JdbcType.VARCHAR),
        @Result(column="department", property="department", jdbcType=JdbcType.VARCHAR),
        @Result(column="note", property="note", jdbcType=JdbcType.VARCHAR)
    })
    List<SysUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table otherlogs
     *
     * @mbggenerated
     */
    @Update({
        "update sysuser",
        "set loginname = #{loginname,jdbcType=VARCHAR},",
          "username = #{username,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "flag = #{flag,jdbcType=VARCHAR},",
          "telphone = #{telphone,jdbcType=BIGINT},",
          "qq = #{qq,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "weixin = #{weixin,jdbcType=VARCHAR},",
          "department = #{department,jdbcType=VARCHAR},",
          "note = #{note,jdbcType=VARCHAR},",
        "where userid = #{userid,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(SysUser user);
    
    @Select({
        "select",
        "userid, loginname, username, password, flag, telphone, qq, email, weixin, department, note ",
        "from sysuser",
        "where loginname = #{loginname,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="userid", property="userid", jdbcType=JdbcType.BIGINT, id=true),
        @Result(column="loginname", property="loginname", jdbcType=JdbcType.VARCHAR),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="flag", property="flag", jdbcType=JdbcType.BIGINT),
        @Result(column="telphone", property="telphone", jdbcType=JdbcType.VARCHAR),
        @Result(column="qq", property="qq", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="weixin", property="weixin", jdbcType=JdbcType.VARCHAR),
        @Result(column="department", property="department", jdbcType=JdbcType.VARCHAR),
        @Result(column="note", property="note", jdbcType=JdbcType.VARCHAR)
    })
    SysUser selectByLoginName(String loginname);
}